global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape metrics from OTEL Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
